#!/bin/bash

# Will be executed as user "root".

# Name this file "daemon" in your plugin-archive. It will be renamed to NAME
# during installation

loxberryhome=REPLACEINSTALLFOLDER
pluginname=REPLACEFOLDERNAME

# Directory/Pluginname fallback for test environment
if [ ! -d $loxberryhome ]; then
	loxberryhome=/opt/loxberry
fi
if [ ! -d $pluginname ]; then
	pluginname=developertools
fi

/usr/bin/logger "loxberry-plugin-$pluginname - DAEMON Script"
	
# Add Any-Plugin to sudoers (need root permission)
# Sudoers V1
# sudoversion=1

chmod -R 774 $loxberryhome/data/plugins/$pluginname

# Add bash shortcuts
awk -v s="alias ls='ls -l --color'" '/^alias ls=/{$0=s;f=1} {a[++n]=$0} END{if(!f)a[++n]=s;for(i=1;i<=n;i++)print a[i]>ARGV[1]}' /etc/bash.bashrc
awk -v s="alias aerr='less $loxberryhome/log/system/apache2/error.log'" '/^alias aerr=/{$0=s;f=1} {a[++n]=$0} END{if(!f)a[++n]=s;for(i=1;i<=n;i++)print a[i]>ARGV[1]}' /etc/bash.bashrc
awk -v s="alias cd..='cd ..'" '/^alias cd..=/{$0=s;f=1} {a[++n]=$0} END{if(!f)a[++n]=s;for(i=1;i<=n;i++)print a[i]>ARGV[1]}' /etc/bash.bashrc

# Enable SSH root login
awk -v s="PermitRootLogin yes" '/^PermitRootLogin/{$0=s;f=1} {a[++n]=$0} END{if(!f)a[++n]=s;for(i=1;i<=n;i++)print a[i]>ARGV[1]}' /etc/ssh/sshd_config

# Create samba share
cat /etc/samba/smb.conf | grep [\[]root[\]]
if [ $? -ne 0 ]; then
	echo [root] >> /etc/samba/smb.conf
	echo comment = Full Access >> /etc/samba/smb.conf
	echo path = / >> /etc/samba/smb.conf
	echo guest ok = no >> /etc/samba/smb.conf
	echo read only = no >> /etc/samba/smb.conf
	echo directory mask = 0700 >> /etc/samba/smb.conf
	echo create mask = 0700 >> /etc/samba/smb.conf

	# Adding root password "loxberry" to user root
	(echo "loxberry"; echo "loxberry") | smbpasswd -s -a root
fi

if [ ! -f /etc/profile.d/$pluginname ]; then
	echo export PATH=$PATH:$loxberryhome/data/plugins/$pluginname > /etc/profile.d/$pluginname 
fi

exit 0
